pattern = 'v0.1.%d'
message-template = "Created {version} for release."

[cargo]

[artifact.mac]
paths = {clu = "mac/clu"}
compress = { name = "clu-mac.tar.gz", format = "tgz" }
target = "GitHub"

[artifact.linux]
paths = {clu = "linux/clu"}
compress = { name = "clu-linux.tar.gz", format = "tgz" }
target = "GitHub"