[targets.dummy-repo]
repo = 'git@github.com:ethankhall/dummy-repo.git'
skip = false

[targets.dummy-repo.pull-request]
pr_number = 14
url = 'https://github.com/ethankhall/dummy-repo/pull/14'

[checkout]
branch-name = 'ethankhall/foo-example'
pre-flight = '/usr/bin/true'

[pr]
title = 'Example Title 2'
description = '''
2 This is a TOML file

So you can add newlines between the PR's'''

[[steps]]
name = 'Example'
migration-script = 'examples/example-migration.sh'
